Oracle安装

diff --git a/scripts/DataBase/mysql/install/configslave b/scripts/DataBase/mysql/install/configslave
--- a/scripts/DataBase/mysql/install/configslave
+++ b/scripts/DataBase/mysql/install/configslave
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-usage(){
+usage() {
     pname=$(basename $0)
     echo "Usage:"
     echo "$pname --rootpwd <root login use password> --masterip <mysql master ip>"
@@ -20,7 +20,7 @@ parseOpts() {
             masterip)
                 masterIp="${!OPTIND}"
                 OPTIND=$(($OPTIND + 1))
-            ;;
+                ;;
             *)
                 if [ "$OPTERR" = 1 ] && [ "${OPT_SPEC:0:1}" != ":" ]; then
                     echo "Unknown option -- ${OPTARG}" >&2
@@ -43,7 +43,7 @@ parseOpts() {
 parseOpts "$@"
 
 function DO_CMD() {
-    echo Exec ommand: $@
+    echo Exec command: $@
     $@
 
     if [ $? != 0 ]; then
@@ -59,31 +59,29 @@ DO_CMD service mysql stop
 
 DO_CMD sed -bi 's/^\s*server_id\s*=.*$/server_id=2/g' /etc/my.cnf
 DO_CMD sed -bi 's/^\s*#\s*log-slave-updates\s*=.*$/log-slave-updates=1/g' /etc/my.cnf
-DO_CMD echo  "relay_log=relay-bin-log" >> /etc/my.cnf
+DO_CMD echo "relay_log=relay-bin-log" >>/etc/my.cnf
 
 DO_CMD service mysql start
 
-mysql -v --connect-expired-password  -uroot -p$rootpwd << EOF
+mysql -v --connect-expired-password -uroot -p$rootpwd <<EOF
         stop slave;
         CHANGE MASTER TO MASTER_HOST='$masterIp',MASTER_USER='root',MASTER_PASSWORD='$rootpwd',MASTER_LOG_FILE='$binLogFile',MASTER_LOG_POS=$binLogOffset;
         start slave;
         show slave status\\G;
 EOF
 
-if [ $? != 0 ]
-then
-	echo "ERROR: set slave bin-log start postion failed."
-	exit 1;
+if [ $? != 0 ]; then
+    echo "ERROR: set slave bin-log start postion failed."
+    exit 1
 fi
 
-errorState=`
-mysql -uroot -p$rootpwd 2>/dev/null << EOF | grep -i Last_IO_Errno: | awk '{print $2}'
-	show slave status\\G;
+errorState=$(
+    mysql -uroot -p$rootpwd 2>/dev/null <<EOF | grep -i Last_IO_Errno: | awk '{print $2}'
+	show slave status\G;
 EOF
-`
+)
 
-if [ ! -z "$errorState" ]
-then
-	echo "ERROR: error slave state."
-	exit 1;
+if [ ! -z "$errorState" ]; then
+    echo "ERROR: error slave state."
+    exit 1
 fi
diff --git a/scripts/DataBase/oracle/install/ora-db-create b/scripts/DataBase/oracle/install/ora-db-create
--- a/scripts/DataBase/oracle/install/ora-db-create
+++ b/scripts/DataBase/oracle/install/ora-db-create
@@ -1,7 +1,7 @@
 #!/bin/bash
 HAS_ERROR=0
 function DO_CMD() {
-    echo Exec ommand: $@
+    echo Exec command: $@
     $@
     EXIT_CODE=$?
     if [ $EXIT_CODE != 0 ]; then
@@ -16,7 +16,7 @@ function DO_CMD() {
 function SUDO_ORA_CMD() {
     USER=$1
     shift
-    echo "Exec ommand: su - '$USER' -c '$@'"
+    echo "Exec command: su - '$USER' -c '$@'"
     eval "su - '$USER' -c '$@'"
     exitCode=$?
     if [ $exitCode -ge 128 ]; then
@@ -33,7 +33,7 @@ function SUDO_ORA_CMD() {
 function SUDO_CMD_CONT() {
     USER=$1
     shift
-    echo "Exec ommand: su - '$USER' -c '$@'"
+    echo "Exec command: su - '$USER' -c '$@'"
     eval "su - '$USER' -c 'AUTOEXEC_JOBID=$AUTOEXEC_JOBID $@'"
     EXIT_CODE=$?
     if [ $EXIT_CODE != 0 ]; then
@@ -41,16 +41,6 @@ function SUDO_CMD_CONT() {
         echo WARN: Execute $@ failed.
     else
         echo FINE: Execute success.
-    fi
-}
-
-function setInstallEnv() {
-    EXEC_ENV_TXT=$(echo "$EXEC_ENV" | perl -pe 's/\\n/\n/g' | perl -pe 's/\s*=\s*/=/g')
-    if [ -n "$EXEC_ENV_TXT" ]; then
-        eval "$EXEC_ENV_TXT"
-    else
-        echo "ERROR: Execute env is empty, must defined by option --EXEC_ENV."
-        exit 2
     fi
 }
 
@@ -68,6 +58,10 @@ function parseOpts() {
                 ;;
             RESPONSE_FILE)
                 RESPONSE_FILE="${!OPTIND}"
+                OPTIND=$(($OPTIND + 1))
+                ;;
+            ORACLE_USER)
+                ORACLE_USER="${!OPTIND}"
                 OPTIND=$(($OPTIND + 1))
                 ;;
             DATABASE_TYPE)
@@ -132,25 +126,9 @@ function parseOpts() {
 
 parseOpts "$@"
 
-oraEnv=$(SUCALL_ORA_CMD $ORACLE_USER env | grep ORACLE_)
+oraEnv=$(SUDO_ORA_CMD $ORACLE_USER env | grep ORACLE_)
 echo "$oraEnv"
-EXEC_ENV=$oraEnv
-setInstallEnv
-
-if [ -n "$RESPONSE_FILE" ]; then
-    if [ ! -e "$RESPONSE_FILE" ]; then
-        echo "ERROR: Response file:$RESPONSE_FILE not exists."
-        exit 3
-    else
-        REAL_RESPONSE_FILE=$ORACLE_HOME/assistants/dbca/dbca_auto.rsp
-        echo "Copy $RESPONSE_FILE to $REAL_RESPONSE_FILE."
-        cp $RESPONSE_FILE "$REAL_RESPONSE_FILE" && chown $ORACLE_USER:$UNIX_GROUP_NAME "$REAL_RESPONSE_FILE"
-        if [ $? != 0 ]; then
-            echo "ERROR: Copy $RESPONSE_FILE to $REAL_RESPONSE_FILE failed."
-            exit 4
-        fi
-    fi
-fi
+eval "$oraEnv"
 
 PDB_COUNT="0"
 if [ "$IS_CDB" == "true" ] && [ -n "$PDB_NAME" ]; then
@@ -175,6 +153,21 @@ fi
 ENV_DISTID=""
 if [ "$CV_ASSUME_DISTID" != "AUTO" ]; then
     ENV_DISTID="CV_ASSUME_DISTID=$CV_ASSUME_DISTID"
+fi
+
+if [ -n "$RESPONSE_FILE" ]; then
+    if [ ! -e "$RESPONSE_FILE" ]; then
+        echo "ERROR: Response file:$RESPONSE_FILE not exists."
+        exit 3
+    else
+        REAL_RESPONSE_FILE=$ORACLE_HOME/assistants/dbca/dbca_auto.rsp
+        echo "Copy $RESPONSE_FILE to $REAL_RESPONSE_FILE."
+        cp $RESPONSE_FILE "$REAL_RESPONSE_FILE" && chown $ORACLE_USER "$REAL_RESPONSE_FILE"
+        if [ $? != 0 ]; then
+            echo "ERROR: Copy $RESPONSE_FILE to $REAL_RESPONSE_FILE failed."
+            exit 4
+        fi
+    fi
 fi
 
 #创建数据库
diff --git a/scripts/DataBase/oracle/install/rac/grid-clean b/scripts/DataBase/oracle/install/rac/grid-clean
--- a/scripts/DataBase/oracle/install/rac/grid-clean
+++ b/scripts/DataBase/oracle/install/rac/grid-clean
@@ -2,7 +2,7 @@
 
 HAS_ERROR=0
 function DO_CMD() {
-    echo Exec ommand: $@
+    echo Exec command: $@
     $@
     EXIT_CODE=$?
     if [ $EXIT_CODE != 0 ]; then
@@ -17,7 +17,7 @@ function DO_CMD() {
 function SUDO_CMD() {
     USER=$1
     shift
-    echo "Exec ommand: su - '$USER' -c '$@'"
+    echo "Exec command: su - '$USER' -c '$@'"
     eval "su - '$USER' -c '$@'"
     EXIT_CODE=$?
     if [ $EXIT_CODE != 0 ]; then
@@ -29,38 +29,21 @@ function SUDO_CMD() {
     fi
 }
 
-function CALL_ORA_CMD() {
-    echo Exec ommand: $@
-    $@
-    exitCode=$?
-    if [ $exitCode -ge 128 ]; then
-        #负数返回码，大于127就是负数的补码
-        echo "ERROR: Installation failed, exitCode:$exitCode."
-    elif [ $exitCode -gt 0 ]; then
-        echo "WARN: Installation has some warning, exitCode:$exitCode."
-    else
-        echo "FINE: All installations were successful."
-    fi
-
-    return $exitCode
-}
-
-function SUCALL_ORA_CMD() {
+function SUDO_ORA_CMD() {
     USER=$1
     shift
-    echo "Exec ommand: su - '$USER' -c '$@'"
+    echo "Exec command: su - '$USER' -c '$@'"
     eval "su - '$USER' -c '$@'"
     exitCode=$?
     if [ $exitCode -ge 128 ]; then
         #负数返回码，大于127就是负数的补码
-        echo "ERROR: Installation failed, exitCode:$exitCode."
+        echo "ERROR: Execute command failed, exitCode:$exitCode."
+        exit $exitCode
     elif [ $exitCode -gt 0 ]; then
-        echo "WARN: Installation has some warning, exitCode:$exitCode."
+        echo "WARN: Execute command  has some warning, exitCode:$exitCode."
     else
-        echo "FINE: All installations were successful."
+        echo "FINE: All operations were successful."
     fi
-
-    return $exitCode
 }
 
 function setInstallEnv() {
@@ -99,8 +82,8 @@ function manualUnInstall() {
         INVENTORY_LOCATION=$(cat $ORACLE_HOME/oraInst.loc | grep inventory_loc | sed s'/inventory_loc\s*=\s*//' | sed s'/\s*$//')
 
         #kill oracle process
-        SUCALL_ORA_CMD $GRID_USER shutdown immediate
-        SUCALL_ORA_CMD $GRID_USER lsnrctl stop
+        SUDO_ORA_CMD $GRID_USER shutdown immediate
+        SUDO_ORA_CMD $GRID_USER lsnrctl stop
         pkill -u $GRID_USER
         sleep 5
         pkill -u $GRID_USER
@@ -227,7 +210,7 @@ fi
 
 #如果没有给出环境变量，则可能是直接执行强制删除Oracle，直接获取用户环境变狼
 if [ -z "$EXEC_ENV" ] && [ -n "$GRID_UID" ]; then
-    EXEC_ENV=$(SUCALL_ORA_CMD $GRID_USER env | grep ORACLE_)
+    EXEC_ENV=$(SUDO_ORA_CMD $GRID_USER env | grep ORACLE_)
 fi
 if [ -n "$EXEC_ENV" ]; then
     setInstallEnv
diff --git a/scripts/DataBase/oracle/install/rac/grid-uninstall b/scripts/DataBase/oracle/install/rac/grid-uninstall
--- a/scripts/DataBase/oracle/install/rac/grid-uninstall
+++ b/scripts/DataBase/oracle/install/rac/grid-uninstall
@@ -2,7 +2,7 @@
 
 HAS_ERROR=0
 function DO_CMD() {
-    echo Exec ommand: $@
+    echo Exec command: $@
     $@
     EXIT_CODE=$?
     if [ $EXIT_CODE != 0 ]; then
@@ -14,38 +14,21 @@ function DO_CMD() {
     fi
 }
 
-function CALL_ORA_CMD() {
-    echo Exec ommand: $@
-    $@
-    exitCode=$?
-    if [ $exitCode -ge 128 ]; then
-        #负数返回码，大于127就是负数的补码
-        echo "ERROR: Installation failed, exitCode:$exitCode."
-    elif [ $exitCode -gt 0 ]; then
-        echo "WARN: Installation has some warning, exitCode:$exitCode."
-    else
-        echo "FINE: All installations were successful."
-    fi
-
-    return $exitCode
-}
-
-function SUCALL_ORA_CMD() {
+function SUDO_ORA_CMD() {
     USER=$1
     shift
-    echo "Exec ommand: su - '$USER' -c '$@'"
+    echo "Exec command: su - '$USER' -c '$@'"
     eval "su - '$USER' -c '$@'"
     exitCode=$?
     if [ $exitCode -ge 128 ]; then
         #负数返回码，大于127就是负数的补码
-        echo "ERROR: Installation failed, exitCode:$exitCode."
+        echo "ERROR: Execute command failed, exitCode:$exitCode."
+        exit $exitCode
     elif [ $exitCode -gt 0 ]; then
-        echo "WARN: Installation has some warning, exitCode:$exitCode."
+        echo "WARN: Execute command  has some warning, exitCode:$exitCode."
     else
-        echo "FINE: All installations were successful."
+        echo "FINE: All operations were successful."
     fi
-
-    return $exitCode
 }
 
 function removeUserAndGroups() {
@@ -67,18 +50,6 @@ function removeUserAndGroups() {
 
     #delete GRID_USER
     userdel $GRID_USER
-}
-
-function setInstallEnv() {
-    #输入的EXEC_ENV是textarea格式，把符号'\n'替换为真正的换行符号
-    #然后eval为shell的变量
-    EXEC_ENV_TXT=$(echo "$EXEC_ENV" | perl -pe 's/\\n/\n/g' | perl -pe 's/\s*=\s*/=/g')
-    if [ -n "$EXEC_ENV_TXT" ]; then
-        eval "$EXEC_ENV_TXT"
-    else
-        echo "ERROR: Execute env is empty, must defined by option --EXEC_ENV."
-        exit 2
-    fi
 }
 
 #参数处理,全部用长参数
@@ -137,17 +108,16 @@ if [ "$CV_ASSUME_DISTID" != "AUTO" ]; then
     ENV_DISTID="CV_ASSUME_DISTID=$CV_ASSUME_DISTID"
 fi
 
-oraEnv=$(SUCALL_ORA_CMD $GRID_USER env | grep ORACLE_)
+oraEnv=$(SUDO_ORA_CMD $GRID_USER env | grep ORACLE_)
 echo "$oraEnv"
-EXEC_ENV=$oraEnv
-setInstallEnv
+eval "$oraEnv"
 
 if [ ! -f "$ORACLE_HOME/deinstall/deinstall" ]; then
     echo "WARN: Deinstall script $ORACLE_HOME/deinstall/deinstall not exists."
     exit 0
 fi
 
-SUCALL_ORA_CMD $GRID_USER $ENV_DISTID LANG=en_US.UTF-8 $ORACLE_HOME/deinstall/deinstall -silent -checkonly -o /tmp | tee oragridunins_check.out
+SUDO_ORA_CMD $GRID_USER $ENV_DISTID LANG=en_US.UTF-8 $ORACLE_HOME/deinstall/deinstall -silent -checkonly -o /tmp | tee oragridunins_check.out
 exitCode=$?
 if [ $exitCode -ge 128 ]; then
     echo "WARN: Uninstall failed"
@@ -156,7 +126,7 @@ fi
 
 rspFile=$(grep "Location of response file generated:" oragridunins_check.out | cut -d: -f 2)
 
-SUCALL_ORA_CMD $GRID_USER $ENV_DISTID 'LANG=en_US.UTF-8 $ORACLE_HOME/deinstall/deinstall' -silent --paramfile $rspFile | tee oragridunins.out
+SUDO_ORA_CMD $GRID_USER $ENV_DISTID 'LANG=en_US.UTF-8 $ORACLE_HOME/deinstall/deinstall' -silent --paramfile $rspFile | tee oragridunins.out
 exitCode=$?
 if [ $exitCode -ge 128 ]; then
     echo "WARN: Uninstall failed"
diff --git a/scripts/DataBase/oracle/install/rac/rac-db-create b/scripts/DataBase/oracle/install/rac/rac-db-create
--- a/scripts/DataBase/oracle/install/rac/rac-db-create
+++ b/scripts/DataBase/oracle/install/rac/rac-db-create
@@ -1,7 +1,7 @@
 #!/bin/bash
 HAS_ERROR=0
 function DO_CMD() {
-    echo Exec ommand: $@
+    echo Exec command: $@
     $@
     EXIT_CODE=$?
     if [ $EXIT_CODE != 0 ]; then
@@ -16,7 +16,7 @@ function DO_CMD() {
 function SUDO_ORA_CMD() {
     USER=$1
     shift
-    echo "Exec ommand: su - '$USER' -c '$@'"
+    echo "Exec command: su - '$USER' -c '$@'"
     eval "su - '$USER' -c '$@'"
     exitCode=$?
     if [ $exitCode -ge 128 ]; then
@@ -33,7 +33,7 @@ function SUDO_ORA_CMD() {
 function SUDO_CMD_CONT() {
     USER=$1
     shift
-    echo "Exec ommand: su - '$USER' -c '$@'"
+    echo "Exec command: su - '$USER' -c '$@'"
     eval "su - '$USER' -c 'AUTOEXEC_JOBID=$AUTOEXEC_JOBID $@'"
     EXIT_CODE=$?
     if [ $EXIT_CODE != 0 ]; then
@@ -153,21 +153,6 @@ function parseOpts() {
 parseOpts "$@"
 setInstallEnv
 
-if [ -n "$RESPONSE_FILE" ]; then
-    if [ ! -e "$RESPONSE_FILE" ]; then
-        echo "ERROR: Response file:$RESPONSE_FILE not exists."
-        exit 3
-    else
-        REAL_RESPONSE_FILE=$ORACLE_HOME/assistants/dbca/dbca_auto.rsp
-        echo "Copy $RESPONSE_FILE to $REAL_RESPONSE_FILE."
-        cp $RESPONSE_FILE "$REAL_RESPONSE_FILE" && chown $ORACLE_USER:$UNIX_GROUP_NAME "$REAL_RESPONSE_FILE"
-        if [ $? != 0 ]; then
-            echo "ERROR: Copy $RESPONSE_FILE to $REAL_RESPONSE_FILE failed."
-            exit 4
-        fi
-    fi
-fi
-
 PDB_COUNT="0"
 if [ "$IS_CDB" == "true" ] && [ -n "$PDB_NAME" ]; then
     PDB_COUNT="1"
@@ -191,6 +176,21 @@ fi
 ENV_DISTID=""
 if [ "$CV_ASSUME_DISTID" != "AUTO" ]; then
     ENV_DISTID="CV_ASSUME_DISTID=$CV_ASSUME_DISTID"
+fi
+
+if [ -n "$RESPONSE_FILE" ]; then
+    if [ ! -e "$RESPONSE_FILE" ]; then
+        echo "ERROR: Response file:$RESPONSE_FILE not exists."
+        exit 3
+    else
+        REAL_RESPONSE_FILE=$ORACLE_HOME/assistants/dbca/dbca_auto.rsp
+        echo "Copy $RESPONSE_FILE to $REAL_RESPONSE_FILE."
+        cp $RESPONSE_FILE "$REAL_RESPONSE_FILE" && chown $ORACLE_USER:$UNIX_GROUP_NAME "$REAL_RESPONSE_FILE"
+        if [ $? != 0 ]; then
+            echo "ERROR: Copy $RESPONSE_FILE to $REAL_RESPONSE_FILE failed."
+            exit 4
+        fi
+    fi
 fi
 
 #创建数据库
