oracle install 优化

diff --git a/scripts/DataBase/oracle/install/ora-db-install b/scripts/DataBase/oracle/install/ora-db-install
--- a/scripts/DataBase/oracle/install/ora-db-install
+++ b/scripts/DataBase/oracle/install/ora-db-install
@@ -131,6 +131,13 @@ fi
 
 if [ -e "$ORACLE_HOME/runInstaller" ]; then
     INSTALLER_DIR=$ORACLE_HOME
+elif [ -e "$ORACLE_HOME/oui/bin/runInstaller" ]; then
+    INSTALLER_DIR="$ORACLE_HOME/oui/bin"
+fi
+
+if [ ! -e "$INSTALLER_DIR/runInstaller" ]; then
+    echo "ERROR: Install script $INSTALLER_DIR/runInstaller not exists.\n"
+    exit 6
 fi
 
 #Truncate inventory_location dir
@@ -151,7 +158,7 @@ fi
 # You can ignore this code if the prerequisite is optional.
 
 #静默安装DB软件
-SUDO_ORA_CMD $ORACLE_USER $ENV_DISTID $INSTALLER_DIR/runInstaller -silent -force -noconfig -ignorePrereq \
+SUDO_ORA_CMD $ORACLE_USER "cd \"$INSTALLER_DIR\" && $ENV_DISTID ./runInstaller" -silent -force -noconfig -ignorePrereq \
     -responseFile $REAL_RESPONSE_FILE \
     oracle.install.option=INSTALL_DB_SWONLY \
     UNIX_GROUP_NAME=$UNIX_GROUP_NAME \
