Oracle install

diff --git a/scripts/DataBase/oracle/install/ora-db-cfg-autostart b/scripts/DataBase/oracle/install/ora-db-cfg-autostart
--- a/scripts/DataBase/oracle/install/ora-db-cfg-autostart
+++ b/scripts/DataBase/oracle/install/ora-db-cfg-autostart
@@ -73,8 +73,11 @@ echo "$oraEnv"
 eval "$oraEnv"
 
 USER_HOME=$(eval echo ~$ORACLE_HOME)
-mkdir "$ORACLE_HOME/scripts"
-cat > "$ORACLE_HOME/scripts/start_all.sh" <<EOF
+if [ not -e "$ORACLE_HOME/scripts" ]; then
+    mkdir "$ORACLE_HOME/scripts"
+fi
+
+cat >"$ORACLE_HOME/scripts/start_all.sh" <<EOF
 #!/bin/bash
 . /home/oracle/.bash_profile
 export ORAENV_ASK=NO
@@ -84,7 +87,7 @@ export ORAENV_ASK=YES
 dbstart \$ORACLE_HOME
 EOF
 
-cat > "$ORACLE_HOME/scripts/stop_all.sh" <<EOF
+cat >"$ORACLE_HOME/scripts/stop_all.sh" <<EOF
 #!/bin/bash
 . /home/oracle/.bash_profile
 export ORAENV_ASK=NO
@@ -99,7 +102,7 @@ chmod u+x "$ORACLE_HOME/scripts"/*.sh
 
 ps -p1 | grep systemd >/dev/null && initType="systemd" || initType="sysvinit"
 if [ "$initType" == "systemd" ]; then
-    cat > /lib/systemd/system/dbora.service <<EOF
+    cat >/lib/systemd/system/dbora.service <<EOF
 [Unit]
 Description=The Oracle Database Service
 After=syslog.target network.target
@@ -127,30 +130,31 @@ EOF
 
     systemctl daemon-reload
     systemctl start dbora.service
-    systemctl enable dbora.service 2>&1 > /dev/null
+    systemctl enable dbora.service 2>&1 >/dev/null
 else
     OS_TYPE=$(uname -s 2>&1)
+    echo "OS type is :$OS_TYPE"
+
     case "$OS_TYPE" in
-            Linux)
-                    INIT_FILE=/etc/init.d/dbora
-                    ;;
-            FreeBSD)
-                    INIT_FILE=/etc/init.d/dbora
-                    ;;
-            AIX)
-                    INIT_FILE=/etc/dbora
-                    ;;
-            SunOs)
-                    INIT_FILE=/etc/init.d/dbora
-                    ;;
-            *)
-                    echo $"ERROR: OS type $OS_TYPE not support yet."
-                    exit 2
-                    ;;
-            esac
+    Linux)
+        INIT_FILE=/etc/init.d/dbora
+        ;;
+    FreeBSD)
+        INIT_FILE=/etc/init.d/dbora
+        ;;
+    AIX)
+        INIT_FILE=/etc/dbora
+        ;;
+    SunOs)
+        INIT_FILE=/etc/init.d/dbora
+        ;;
+    *)
+        echo $"ERROR: OS type $OS_TYPE not support yet."
+        exit 2
+        ;;
+    esac
 
-
-cat > $INIT_FILE <<EOF
+    cat >$INIT_FILE <<EOF
 #! /bin/sh 
 # description: Oracle auto start-stop script.
 #
@@ -188,29 +192,29 @@ EOF
     chmod 750 $INIT_FILE
 
     case "$OS_TYPE" in
-            Linux)
-                ln -s $INIT_FILE /etc/rc.d/rc0.d/K01dbora
-                ln -s $INIT_FILE /etc/rc.d/rc3.d/S99dbora
-                ln -s $INIT_FILE /etc/rc.d/rc5.d/S99dbora
-                ;;
-            FreeBSD)
-                ln -s $INIT_FILE /etc/rc.d/rc0.d/K01dbora
-                ln -s $INIT_FILE /etc/rc.d/rc3.d/S99dbora
-                ln -s $INIT_FILE /etc/rc.d/rc5.d/S99dbora
-                ;;
-            AIX)
-                ln -s $INIT_FILE /etc/rc.d/rc2.d/S99dbora
-                ln -s $INIT_FILE /etc/rc.d/rc0.d/K01dbora
-                ;;
-            SunOs)
-                ln -s $INIT_FILE /etc/rc0.d/K01dbora
-                ln -s $INIT_FILE /etc/rc3.d/S99dbora
-                    ;;
-            *)
-                echo $"ERROR: OS type $OS_TYPE not support yet."
-                exit 2
-                ;;
-            esac
+    Linux)
+        ln -s $INIT_FILE /etc/rc.d/rc0.d/K01dbora
+        ln -s $INIT_FILE /etc/rc.d/rc3.d/S99dbora
+        ln -s $INIT_FILE /etc/rc.d/rc5.d/S99dbora
+        ;;
+    FreeBSD)
+        ln -s $INIT_FILE /etc/rc.d/rc0.d/K01dbora
+        ln -s $INIT_FILE /etc/rc.d/rc3.d/S99dbora
+        ln -s $INIT_FILE /etc/rc.d/rc5.d/S99dbora
+        ;;
+    AIX)
+        ln -s $INIT_FILE /etc/rc.d/rc2.d/S99dbora
+        ln -s $INIT_FILE /etc/rc.d/rc0.d/K01dbora
+        ;;
+    SunOs)
+        ln -s $INIT_FILE /etc/rc0.d/K01dbora
+        ln -s $INIT_FILE /etc/rc3.d/S99dbora
+        ;;
+    *)
+        echo $"ERROR: OS type $OS_TYPE not support yet."
+        exit 2
+        ;;
+    esac
 fi
 
 if [ -z "$SID" ]; then
@@ -227,4 +231,3 @@ if [ -e /etc/oratab ]; then
     DO_CMD sed -i -e "\|${SID}:${ORACLE_HOME}:N|d" /etc/oratab
 fi
 DO_CMD "echo '${SID}:${ORACLE_HOME}:Y' >> /etc/oratab"
-
diff --git a/scripts/DataBase/oracle/install/rac/rac-db-create b/scripts/DataBase/oracle/install/rac/rac-db-create
--- a/scripts/DataBase/oracle/install/rac/rac-db-create
+++ b/scripts/DataBase/oracle/install/rac/rac-db-create
@@ -113,6 +113,10 @@ function parseOpts() {
                 RESPONSE_FILE="${!OPTIND}"
                 OPTIND=$(($OPTIND + 1))
                 ;;
+            TEMPLATE_FILE)
+                TEMPLATE_FILE="${!OPTIND}"
+                OPTIND=$(($OPTIND + 1))
+                ;;
             EXEC_ENV)
                 EXEC_ENV="${!OPTIND}"
                 OPTIND=$(($OPTIND + 1))
@@ -245,6 +249,24 @@ if [ -n "$RESPONSE_FILE" ]; then
     fi
 fi
 
+if [ -n "$TEMPLATE_FILE" ]; then
+    if [ ! -e "$TEMPLATE_FILE" ]; then
+        echo "ERROR: Template file:$TEMPLATE_FILE not exists."
+        exit 3
+    else
+        REAL_TEMPLATE_FILE=$ORACLE_HOME/assistants/dbca/templates/template_auto.dbc
+        echo "Copy $TEMPLATE_FILE to $REAL_TEMPLATE_FILE."
+        cp $TEMPLATE_FILE "$REAL_TEMPLATE_FILE" && chown $ORACLE_USER:$UNIX_GROUP_NAME "$REAL_TEMPLATE_FILE"
+        if [ $? != 0 ]; then
+            echo "ERROR: Copy $TEMPLATE_FILE to $REAL_TEMPLATE_FILE failed."
+            exit 4
+        fi
+        TEMPLATE_FILE=template_auto.dbc
+    fi
+else
+    TEMPLATE_FILE=General_Purpose.dbc
+fi
+
 if [ -z "$DB_UNIQUE_NAME" ]; then
     DB_UNIQUE_NAME=$DB_NAME
 fi
@@ -256,7 +278,7 @@ SUDO_ORA_CMD $ORACLE_USER $ENV_DISTID $ORACLE_HOME/bin/dbca -silent \
     -responseFile $REAL_RESPONSE_FILE \
     -variables "ORACLE_BASE_HOME=$ORACLE_HOME,DB_UNIQUE_NAME=$DB_UNIQUE_NAME,ORACLE_BASE=$ORACLE_BASE,PDB_NAME=$PDB_NAME,DB_NAME=$DB_NAME,ORACLE_HOME=$ORACLE_HOME,SID=$DB_NAME" \
     -initParams "$INIT_PARAMS" \
-    -templateName General_Purpose.dbc \
+    -templateName "$TEMPLATE_FILE" \
     -gdbname $DB_NAME \
     -sid $DB_NAME \
     -nodelist $NODE_LIST \
