oracle install

diff --git a/scripts/DataBase/oracle/install/19c-rac/dbcreate b/scripts/DataBase/oracle/install/19c-rac/dbcreate
--- a/scripts/DataBase/oracle/install/19c-rac/dbcreate
+++ b/scripts/DataBase/oracle/install/19c-rac/dbcreate
@@ -193,6 +193,17 @@ SUDO_CMD $ORACLE_USER $ORACLE_HOME/bin/dbca -silent \
     -recoveryAreaDestination "+$ARCH_DISKGROUP" \
     -recoveryGroupName "+$ARCH_DISKGROUP"
 
+exitCode=$?
+if [ $exitCode -ge 128 ]; then
+    #负数返回码，大于127就是负数的补码
+    echo "ERROR: Installation failed, exitCode:$exitCode."
+    exit $exitCode
+elif [ $exitCode -ge 0 ]; then
+    echo "WARN: Installation has some warning, exitCode:$exitCode."
+else
+    echo "FINE: All installations were successful."
+fi
+
 #集群验证
 SUDO_CMD $ORACLE_USER crsctl stat res -t
 
diff --git a/scripts/DataBase/oracle/install/19c-rac/dbins b/scripts/DataBase/oracle/install/19c-rac/dbins
--- a/scripts/DataBase/oracle/install/19c-rac/dbins
+++ b/scripts/DataBase/oracle/install/19c-rac/dbins
@@ -156,6 +156,18 @@ if [ "$CV_ASSUME_DISTID" != "AUTO" ]; then
     ENV_DISTID="CV_ASSUME_DISTID=$CV_ASSUME_DISTID"
 fi
 
+##runInstall exit code##
+# 0	All installations were successful.
+# 1	All installations were successful, but some optional configuration tools failed.
+# 2	Local installations were successful, but some remote operations failed.
+# 3	All installations were successful, but some recommended configuration tools failed.
+# 4	The installation was stopped.
+# 6	The installation was successful after you proceeded by disregarding a few prerequisite checks or warnings.
+# -1	At least one installation failed.
+# -2	The installation failed. One or more validation of variables failed.
+# -3	The attempted installation encountered a prerequisite failure. Some of the optional prerequisites have not been met. See the logs for details.
+# You can ignore this code if the prerequisite is optional.
+
 #静默安装DB软件
 SUDO_CMD $ORACLE_USER $ENV_DISTID $ORACLE_HOME/runInstaller -silent -force -noconfig -ignorePrereq \
     -responseFile $REAL_RESPONSE_FILE \
@@ -172,5 +184,17 @@ SUDO_CMD $ORACLE_USER $ENV_DISTID $ORACLE_HOME/runInstaller -silent -force -noco
     oracle.install.db.OSKMDBA_GROUP=$OSKMDBA_GROUP \
     oracle.install.db.OSRACDBA_GROUP=$OSRACDBA_GROUP \
     oracle.install.db.CLUSTER_NODES=$CLUSTER_NODES
+
+exitCode=$?
+if [ $exitCode -ge 128 ]; then
+    #负数返回码，大于127就是负数的补码
+    HAS_ERROR=1
+    echo "ERROR: Installation failed, exitCode:$exitCode."
+elif [ $exitCode -ge 0 ]; then
+    HAS_WARN=1
+    echo "WARN: Installation has some warning, exitCode:$exitCode."
+else
+    echo "FINE: All installations were successful."
+fi
 
 exit $HAS_ERROR
diff --git a/scripts/DataBase/oracle/install/19c-rac/gridins b/scripts/DataBase/oracle/install/19c-rac/gridins
--- a/scripts/DataBase/oracle/install/19c-rac/gridins
+++ b/scripts/DataBase/oracle/install/19c-rac/gridins
@@ -234,4 +234,16 @@ SUDO_CMD $GRID_USER $ENV_DISTID "$ORACLE_HOME/gridSetup.sh" -ignorePrereq -waitf
     oracle.install.asm.monitorPassword=$ASM_PWD \
     oracle.install.asm.configureAFD=false
 
+exitCode=$?
+if [ $exitCode -ge 128 ]; then
+    #负数返回码，大于127就是负数的补码
+    HAS_ERROR=1
+    echo "ERROR: Installation failed, exitCode:$exitCode."
+elif [ $exitCode -ge 0 ]; then
+    HAS_WARN=1
+    echo "WARN: Installation has some warning, exitCode:$exitCode."
+else
+    echo "FINE: All installations were successful."
+fi
+
 exit $HAS_ERROR
diff --git a/scripts/DataBase/oracle/install/dbins-root b/scripts/DataBase/oracle/install/dbins-root
--- a/scripts/DataBase/oracle/install/dbins-root
+++ b/scripts/DataBase/oracle/install/dbins-root
@@ -29,13 +29,20 @@ function SUDO_CMD() {
 }
 
 ORACLE_HOME=$1
-
-if [ -n "$ORACLE_HOME" ]; then
+if [ -z "$ORACLE_HOME" ]; then
     echo "ERROR: Argument not provided."
     echo "Usage: dbins-root <Oracle Home dir>"
     exit 2
 fi
 
-DO_CMD $ORACLE_HOME/root.sh
-
-exit $HAS_ERROR
+$ORACLE_HOME/root.sh
+exitCode=$?
+if [ $exitCode -ge 128 ]; then
+    #负数返回码，大于127就是负数的补码
+    echo "ERROR: Execute $ORACLE_HOME/root.sh failed, exitCode:$exitCode."
+    exit $exitCode
+elif [ $exitCode -ge 0 ]; then
+    echo "WARN: Execute $ORACLE_HOME/root.sh has some warning, exitCode:$exitCode."
+else
+    echo "FINE: Execute $ORACLE_HOME/root.sh successful."
+fi
diff --git a/scripts/DataBase/oracle/install/gridins-root b/scripts/DataBase/oracle/install/gridins-root
--- a/scripts/DataBase/oracle/install/gridins-root
+++ b/scripts/DataBase/oracle/install/gridins-root
@@ -29,7 +29,7 @@ function SUDO_CMD() {
 }
 
 GRID_HOME=$1
-if [ -z "$ORACLE_HOME" ]; then
+if [ -z "$GRID_HOME" ]; then
     echo "ERROR: Argument not provided."
     echo "Usage: dbins-root <Oracle Home dir>"
     exit 2
@@ -42,7 +42,27 @@ if [ -z "$INVENTORY_DIR" ]; then
     exit 3
 fi
 
-DO_CMD $INVENTORY_LOCATION/orainstRoot.sh
-DO_CMD $GRID_HOME/root.sh
+$INVENTORY_LOCATION/orainstRoot.sh
+exitCode=$?
+if [ $exitCode -ge 128 ]; then
+    #负数返回码，大于127就是负数的补码
+    echo "ERROR: Execute $INVENTORY_LOCATION/orainstRoot.sh failed, exitCode:$exitCode."
+    exit $exitCode
+elif [ $exitCode -ge 0 ]; then
+    echo "WARN: Execute $INVENTORY_LOCATION/orainstRoot.sh has some warning, exitCode:$exitCode."
+else
+    echo "FINE: Execute $INVENTORY_LOCATION/orainstRoot.sh successful."
+fi
 
-exit $HAS_ERROR
+$GRID_HOME/root.sh
+exitCode=$?
+if [ $exitCode -ge 128 ]; then
+    #负数返回码，大于127就是负数的补码
+    echo "ERROR: Execute $GRID_HOME/root.sh failed, exitCode:$exitCode."
+    exit $exitCode
+elif [ $exitCode -ge 0 ]; then
+    echo "WARN: Execute $GRID_HOME/root.sh has some warning, exitCode:$exitCode."
+else
+    echo "FINE: Execute $GRID_HOME/root.sh successful."
+fi
+
