oracle install

diff --git a/scripts/DataBase/oracle/install/19c-rac/dbcreate b/scripts/DataBase/oracle/install/19c-rac/dbcreate
--- a/scripts/DataBase/oracle/install/19c-rac/dbcreate
+++ b/scripts/DataBase/oracle/install/19c-rac/dbcreate
@@ -13,16 +13,32 @@ function DO_CMD() {
     fi
 }
 
-function SUDO_CMD() {
+function SUDO_ORA_CMD() {
     USER=$1
     shift
     echo "Exec ommand: su - '$USER' -c '$@'"
     eval "su - '$USER' -c '$@'"
+    exitCode=$?
+    if [ $exitCode -ge 128 ]; then
+        #负数返回码，大于127就是负数的补码
+        echo "ERROR: Installation failed, exitCode:$exitCode."
+        exit $exitCode
+    elif [ $exitCode -gt 0 ]; then
+        echo "WARN: Installation has some warning, exitCode:$exitCode."
+    else
+        echo "FINE: All installations were successful."
+    fi
+}
+
+function SUDO_CMD_CONT() {
+    USER=$1
+    shift
+    echo "Exec ommand: su - '$USER' -c '$@'"
+    eval "su - '$USER' -c 'AUTOEXEC_JOBID=$AUTOEXEC_JOBID $@'"
     EXIT_CODE=$?
     if [ $EXIT_CODE != 0 ]; then
-        HAS_ERROR=1
-        echo ERROR: Execute $@ failed.
-        exit $EXIT_CODE
+        HAS_WARN=1
+        echo WARN: Execute $@ failed.
     else
         echo FINE: Execute success.
     fi
@@ -162,7 +178,7 @@ fi
 
 #创建数据库
 #su - oracle
-SUDO_CMD $ORACLE_USER $ORACLE_HOME/bin/dbca -silent \
+SUDO_ORA_CMD $ORACLE_USER $ORACLE_HOME/bin/dbca -silent \
     -responseFile $REAL_RESPONSE_FILE \
     -variables "ORACLE_BASE_HOME=$ORACLE_HOME,DB_UNIQUE_NAME=$DB_UNIQUE_NAME,ORACLE_BASE=$ORACLE_BASE,PDB_NAME=$PDB_NAME,DB_NAME=$DB_UNIQUE_NAME,ORACLE_HOME=$ORACLE_HOME,SID=$DB_UNIQUE_NAME" \
     -createDatabase \
@@ -193,18 +209,7 @@ SUDO_CMD $ORACLE_USER $ORACLE_HOME/bin/dbca -silent \
     -recoveryAreaDestination "+$ARCH_DISKGROUP" \
     -recoveryGroupName "+$ARCH_DISKGROUP"
 
-exitCode=$?
-if [ $exitCode -ge 128 ]; then
-    #负数返回码，大于127就是负数的补码
-    echo "ERROR: Installation failed, exitCode:$exitCode."
-    exit $exitCode
-elif [ $exitCode -ge 0 ]; then
-    echo "WARN: Installation has some warning, exitCode:$exitCode."
-else
-    echo "FINE: All installations were successful."
-fi
-
 #集群验证
-SUDO_CMD $ORACLE_USER crsctl stat res -t
+SUDO_CMD_CONT $ORACLE_USER crsctl stat res -t
 
 exit $HAS_ERROR
diff --git a/scripts/DataBase/oracle/install/19c-rac/dbins b/scripts/DataBase/oracle/install/19c-rac/dbins
--- a/scripts/DataBase/oracle/install/19c-rac/dbins
+++ b/scripts/DataBase/oracle/install/19c-rac/dbins
@@ -28,18 +28,20 @@ function DO_CMD() {
     fi
 }
 
-function SUDO_CMD() {
+function SUDO_ORA_CMD() {
     USER=$1
     shift
     echo "Exec ommand: su - '$USER' -c '$@'"
     eval "su - '$USER' -c '$@'"
-    EXIT_CODE=$?
-    if [ $EXIT_CODE != 0 ]; then
-        HAS_ERROR=1
-        echo ERROR: Execute $@ failed.
-        exit $EXIT_CODE
+    exitCode=$?
+    if [ $exitCode -ge 128 ]; then
+        #负数返回码，大于127就是负数的补码
+        echo "ERROR: Installation failed, exitCode:$exitCode."
+        exit $exitCode
+    elif [ $exitCode -gt 0 ]; then
+        echo "WARN: Installation has some warning, exitCode:$exitCode."
     else
-        echo FINE: Execute success.
+        echo "FINE: All installations were successful."
     fi
 }
 
@@ -169,7 +171,7 @@ fi
 # You can ignore this code if the prerequisite is optional.
 
 #静默安装DB软件
-SUDO_CMD $ORACLE_USER $ENV_DISTID $ORACLE_HOME/runInstaller -silent -force -noconfig -ignorePrereq \
+SUDO_ORA_CMD $ORACLE_USER $ENV_DISTID $ORACLE_HOME/runInstaller -silent -force -noconfig -ignorePrereq \
     -responseFile $REAL_RESPONSE_FILE \
     oracle.install.option=INSTALL_DB_SWONLY \
     UNIX_GROUP_NAME=$UNIX_GROUP_NAME \
@@ -184,17 +186,5 @@ SUDO_CMD $ORACLE_USER $ENV_DISTID $ORACLE_HOME/runInstaller -silent -force -noco
     oracle.install.db.OSKMDBA_GROUP=$OSKMDBA_GROUP \
     oracle.install.db.OSRACDBA_GROUP=$OSRACDBA_GROUP \
     oracle.install.db.CLUSTER_NODES=$CLUSTER_NODES
-
-exitCode=$?
-if [ $exitCode -ge 128 ]; then
-    #负数返回码，大于127就是负数的补码
-    HAS_ERROR=1
-    echo "ERROR: Installation failed, exitCode:$exitCode."
-elif [ $exitCode -ge 0 ]; then
-    HAS_WARN=1
-    echo "WARN: Installation has some warning, exitCode:$exitCode."
-else
-    echo "FINE: All installations were successful."
-fi
 
 exit $HAS_ERROR
diff --git a/scripts/DataBase/oracle/install/19c-rac/gridins b/scripts/DataBase/oracle/install/19c-rac/gridins
--- a/scripts/DataBase/oracle/install/19c-rac/gridins
+++ b/scripts/DataBase/oracle/install/19c-rac/gridins
@@ -36,18 +36,20 @@ function DO_CMD() {
     fi
 }
 
-function SUDO_CMD() {
+function SUDO_ORA_CMD() {
     USER=$1
     shift
     echo "Exec ommand: su - '$USER' -c '$@'"
     eval "su - '$USER' -c 'AUTOEXEC_JOBID=$AUTOEXEC_JOBID $@'"
-    EXIT_CODE=$?
-    if [ $EXIT_CODE != 0 ]; then
-        HAS_ERROR=1
-        echo ERROR: Execute $@ failed.
-        exit $EXIT_CODE
+    exitCode=$?
+    if [ $exitCode -ge 128 ]; then
+        #负数返回码，大于127就是负数的补码
+        echo "ERROR: Installation failed, exitCode:$exitCode."
+        exit $exitCode
+    elif [ $exitCode -gt 0 ]; then
+        echo "WARN: Installation has some warning, exitCode:$exitCode."
     else
-        echo FINE: Execute success.
+        echo "FINE: All installations were successful."
     fi
 }
 
@@ -211,7 +213,7 @@ fi
 #SUDO_CMD_CONT $GRID_USER $ENV_DISTID "$ORACLE_HOME/runcluvfy.sh" stage -pre crsinst -n "$DB_NODES" -verbose -orainv $UNIX_GROUP_NAME
 
 #执行安装
-SUDO_CMD $GRID_USER $ENV_DISTID "$ORACLE_HOME/gridSetup.sh" -ignorePrereq -waitforcompletion -silent \
+SUDO_ORA_CMD $GRID_USER $ENV_DISTID "$ORACLE_HOME/gridSetup.sh" -ignorePrereq -waitforcompletion -silent \
     -responseFile $REAL_RESPONSE_FILE \
     INVENTORY_LOCATION=$INVENTORY_LOCATION \
     oracle.install.option=CRS_CONFIG \
@@ -233,17 +235,5 @@ SUDO_CMD $GRID_USER $ENV_DISTID "$ORACLE_HOME/gridSetup.sh" -ignorePrereq -waitf
     oracle.install.asm.SYSASMPassword=$ASM_PWD \
     oracle.install.asm.monitorPassword=$ASM_PWD \
     oracle.install.asm.configureAFD=false
-
-exitCode=$?
-if [ $exitCode -ge 128 ]; then
-    #负数返回码，大于127就是负数的补码
-    HAS_ERROR=1
-    echo "ERROR: Installation failed, exitCode:$exitCode."
-elif [ $exitCode -ge 0 ]; then
-    HAS_WARN=1
-    echo "WARN: Installation has some warning, exitCode:$exitCode."
-else
-    echo "FINE: All installations were successful."
-fi
 
 exit $HAS_ERROR
