oracle install script

diff --git a/scripts/DataBase/oracle/install/19c-rac/dbcreate b/scripts/DataBase/oracle/install/19c-rac/dbcreate
--- a/scripts/DataBase/oracle/install/19c-rac/dbcreate
+++ b/scripts/DataBase/oracle/install/19c-rac/dbcreate
@@ -26,6 +26,16 @@ function SUDO_CMD() {
     fi
 }
 
+function setInstallEnv() {
+    EXEC_ENV_TXT=$(echo $EXEC_ENV | perl -pe 's/\\n/\n/g')
+    if [ ! -z "$EXEC_ENV_TXT" ]; then
+        eval "$EXEC_ENV_TXT"
+    else
+        echo "ERROR: Execute env is empty, must defined by option --EXEC_ENV."
+        exit 2
+    fi
+}
+
 #参数处理,全部用长参数
 ######################################
 function parseOpts() {
@@ -107,6 +117,7 @@ function parseOpts() {
 }
 
 parseOpts "$@"
+setInstallEnv
 
 if [ -n "$RESPONSE_FILE"]; then
     RESPONSE_FILE=${RESPONSE_FILE#*\"}
@@ -179,4 +190,6 @@ SUDO_CMD $ORACLE_USER $ORACLE_HOME/bin/dbca -silent \
     -recoveryGroupName "+$ARCH_DISKGROUP"
 
 #集群验证
-crsctl stat res -t
+SUDO_CMD $ORACLE_USER crsctl stat res -t
+
+exit $HAS_ERROR
diff --git a/scripts/DataBase/oracle/install/19c-rac/dbins b/scripts/DataBase/oracle/install/19c-rac/dbins
--- a/scripts/DataBase/oracle/install/19c-rac/dbins
+++ b/scripts/DataBase/oracle/install/19c-rac/dbins
@@ -40,18 +40,28 @@ function SUDO_CMD() {
     fi
 }
 
+function setInstallEnv() {
+    EXEC_ENV_TXT=$(echo $EXEC_ENV | perl -pe 's/\\n/\n/g')
+    if [ ! -z "$EXEC_ENV_TXT" ]; then
+        eval "$EXEC_ENV_TXT"
+    else
+        echo "ERROR: Execute env is empty, must defined by option --EXEC_ENV."
+        exit 2
+    fi
+}
+
 function createOraDir() {
     if [ ! -e "$INVENTORY_LOCATION" ]; then
         mkdir -p $INVENTORY_LOCATION
-        chown -R $ORACLE_USER:$INSTALL_GROUP $INVENTORY_LOCATION
-        chmod -R 775 $INVENTORY_LOCATION
+        DO_CMD chown -R $ORACLE_USER:$INSTALL_GROUP $INVENTORY_LOCATION
+        DO_CMD chmod -R 775 $INVENTORY_LOCATION
     fi
 
     mkdir -p $ORACLE_BASE
     mkdir -p $ORACLE_BASE/cfgtoollogs
     mkdir -p $ORACLE_HOME
-    chown -R $ORACLE_USER:$INSTALL_GROUP $ORACLE_BASE
-    chmod -R 775 $ORACLE_BASE
+    DO_CMD chown -R $ORACLE_USER:$INSTALL_GROUP $ORACLE_BASE
+    DO_CMD chmod -R 775 $ORACLE_BASE
 }
 
 if [ -n "$RESPONSE_FILE"]; then
@@ -112,6 +122,8 @@ function parseOpts() {
 }
 
 parseOpts "$@"
+setInstallEnv
+createOraDir
 
 #unzip安装包到$ORACLE_HOME下，chown oracle:oinstall
 if [ ! -z "$RESPONSE_FILE"]; then
