oracle install

diff --git a/scripts/DataBase/oracle/install/19c-rac/dbcreate b/scripts/DataBase/oracle/install/19c-rac/dbcreate
--- a/scripts/DataBase/oracle/install/19c-rac/dbcreate
+++ b/scripts/DataBase/oracle/install/19c-rac/dbcreate
@@ -23,7 +23,7 @@ function SUDO_ORA_CMD() {
         #负数返回码，大于127就是负数的补码
         echo "ERROR: Installation failed, exitCode:$exitCode."
         exit $exitCode
-    elif [ $exitCode -gt 0 ]; then
+        elif [ $exitCode -gt 0 ]; then
         echo "WARN: Installation has some warning, exitCode:$exitCode."
     else
         echo "FINE: All installations were successful."
@@ -45,8 +45,8 @@ function SUDO_CMD_CONT() {
 }
 
 function setInstallEnv() {
-    EXEC_ENV_TXT=$(echo $EXEC_ENV | perl -pe 's/\\n/\n/g')
-    if [ ! -z "$EXEC_ENV_TXT" ]; then
+    EXEC_ENV_TXT=$(echo "$EXEC_ENV" | perl -pe 's/\\n/\n/g' | perl -pe 's/\s*=\s*/=/g')
+    if [ -n "$EXEC_ENV_TXT" ]; then
         eval "$EXEC_ENV_TXT"
     else
         echo "ERROR: Execute env is empty, must defined by option --EXEC_ENV."
@@ -60,79 +60,91 @@ function parseOpts() {
     OPT_SPEC=":h-:"
     while getopts "$OPT_SPEC" optchar; do
         case "${optchar}" in
-        -)
-            case "${OPTARG}" in
-            RESPONSE_FILE)
-                RESPONSE_FILE="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            EXEC_ENV)
-                EXEC_ENV="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            NODE_LIST)
-                NODE_LIST="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            DATA_DISKGROUP)
-                DATA_DISKGROUP="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            ARCH_DISKGROUP)
-                ARCH_DISKGROUP="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            STORAGE_TYPE)
-                STORAGE_TYPE="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            DATABASE_TYPE)
-                DATABASE_TYPE="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            CDB_PWD)
-                CDB_PWD="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            PWD_PWD)
-                PWD_PWD="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            IS_CDB)
-                IS_CDB="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            DB_UNIQUE_NAME)
-                DB_UNIQUE_NAME="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            PDB_NAME)
-                PDB_NAME="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            AUTO_MEMORY)
-                AUTO_MEMORY="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
-            MEM_PERCENTAGE)
-                MEM_PERCENTAGE="${!OPTIND}"
-                OPTIND=$(($OPTIND + 1))
-                ;;
+            -)
+                case "${OPTARG}" in
+                    CV_ASSUME_DISTID)
+                        CV_ASSUME_DISTID="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    RESPONSE_FILE)
+                        RESPONSE_FILE="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    EXEC_ENV)
+                        EXEC_ENV="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    NODE_LIST)
+                        NODE_LIST="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    DATA_DISKGROUP)
+                        DATA_DISKGROUP="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    ARCH_DISKGROUP)
+                        ARCH_DISKGROUP="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    STORAGE_TYPE)
+                        STORAGE_TYPE="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    DATABASE_TYPE)
+                        DATABASE_TYPE="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    CONFIG_TYPE)
+                        CONFIG_TYPE="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    CHARSET)
+                        CHARSET="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    CDB_PWD)
+                        CDB_PWD="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    PDB_PWD)
+                        PDB_PWD="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    IS_CDB)
+                        IS_CDB="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    DB_UNIQUE_NAME)
+                        DB_UNIQUE_NAME="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    PDB_NAME)
+                        PDB_NAME="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    AUTO_MEMORY)
+                        AUTO_MEMORY="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    MEM_PERCENTAGE)
+                        MEM_PERCENTAGE="${!OPTIND}"
+                        OPTIND=$(($OPTIND + 1))
+                    ;;
+                    *)
+                        if [ "$OPTERR" = 1 ] && [ "${OPT_SPEC:0:1}" != ":" ]; then
+                            echo "Unknown option --${OPTARG}" >&2
+                        fi
+                    ;;
+                esac
+            ;;
+            h)
+                usage
+                exit 2
+            ;;
             *)
-                if [ "$OPTERR" = 1 ] && [ "${OPT_SPEC:0:1}" != ":" ]; then
-                    echo "Unknown option --${OPTARG}" >&2
+                if [ "$OPTERR" != 1 ] || [ "${OPT_SPEC:0:1}" = ":" ]; then
+                    echo "Non-option argument: '-${OPTARG}'" >&2
                 fi
-                ;;
-            esac
-            ;;
-        h)
-            usage
-            exit 2
-            ;;
-        *)
-            if [ "$OPTERR" != 1 ] || [ "${OPT_SPEC:0:1}" = ":" ]; then
-                echo "Non-option argument: '-${OPTARG}'" >&2
-            fi
             ;;
         esac
     done
@@ -141,7 +153,7 @@ function parseOpts() {
 parseOpts "$@"
 setInstallEnv
 
-if [ -n "$RESPONSE_FILE"]; then
+if [ -n "$RESPONSE_FILE" ]; then
     if [ ! -e "$RESPONSE_FILE" ]; then
         echo "ERROR: Response file:$RESPONSE_FILE not exists."
         exit 3
@@ -149,7 +161,7 @@ if [ -n "$RESPONSE_FILE"]; then
         REAL_RESPONSE_FILE=$ORACLE_HOME/assistants/dbca/dbca_auto.rsp
         echo "Copy $RESPONSE_FILE to $REAL_RESPONSE_FILE."
         cp $RESPONSE_FILE "$REAL_RESPONSE_FILE" && chown $GRID_USER:$UNIX_GROUP_NAME "$REAL_RESPONSE_FILE"
-        if [ $?!=0 ]; then
+        if [ $? != 0 ]; then
             echo "ERROR: Copy $RESPONSE_FILE to $REAL_RESPONSE_FILE failed."
             exit 4
         fi
@@ -162,52 +174,56 @@ if [ "$IS_CDB" == "true" ] && [ -n "$PDB_NAME" ]; then
 fi
 
 if [ -z "$ORACLE_USER" ]; then
-    echo "ERROR: Must defined ORACLE_USER with option --EXEC_ENV."
+    echo "ERROR: Must defined ORACLE_USER with option --ORACLE_USER."
     exit 2
 fi
 
 if [ -z "$ORACLE_BASE" ]; then
-    echo "ERROR: Must defined ORACLE_BASE with option --EXEC_ENV."
+    echo "ERROR: Must defined ORACLE_BASE with option --ORACLE_BASE."
     exit 2
 fi
 
 if [ -z "$ORACLE_HOME" ]; then
-    echo "ERROR: Must defined ORACLE_HOME with option --EXEC_ENV."
+    echo "ERROR: Must defined ORACLE_HOME with option --ORACLE_HOME."
     exit 2
+fi
+
+ENV_DISTID=""
+if [ "$CV_ASSUME_DISTID" != "AUTO" ]; then
+    ENV_DISTID="CV_ASSUME_DISTID=$CV_ASSUME_DISTID"
 fi
 
 #创建数据库
 #su - oracle
-SUDO_ORA_CMD $ORACLE_USER $ORACLE_HOME/bin/dbca -silent \
-    -responseFile $REAL_RESPONSE_FILE \
-    -variables "ORACLE_BASE_HOME=$ORACLE_HOME,DB_UNIQUE_NAME=$DB_UNIQUE_NAME,ORACLE_BASE=$ORACLE_BASE,PDB_NAME=$PDB_NAME,DB_NAME=$DB_UNIQUE_NAME,ORACLE_HOME=$ORACLE_HOME,SID=$DB_UNIQUE_NAME" \
-    -createDatabase \
-    -templateName General_Purpose.dbc \
-    -gdbname $DB_UNIQUE_NAME \
-    -sid $DB_UNIQUE_NAME \
-    -nodelist $NODE_LIST \
-    -databaseConfigType=$CONFIG_TYPE \
-    -databaseType $DATABASE_TYPE \
-    -createAsContainerDatabase $IS_CDB \
-    -numberOfPDBs $PDB_COUNT \
-    -pdbName "$PDB_NAME" \
-    -characterSet $CHARSET \
-    -nationalCharacterSet AL16UTF16 \
-    -sysPassword $CDB_PWD \
-    -systemPassword $CDB_PWD \
-    -pdbAdminPassword $PWD_PWD \
-    -dbsnmpPassword $CDB_PWD \
-    -asmsnmpPassword $CDB_PWD \
-    -automaticMemoryManagement $AUTO_MEMORY \
-    -memoryPercentage $MEM_PERCENTAGE \
-    -totalMemory 0 \
-    -emConfiguration NONE \
-    -ignorePreReqs \
-    -storageType $STORAGE_TYPE \
-    -diskGroupName "+$DATA_DISKGROUP/{DB_UNIQUE_NAME}/" \
-    -datafileDestination "+$DATA_DISKGROUP/{DB_UNIQUE_NAME}/" \
-    -recoveryAreaDestination "+$ARCH_DISKGROUP" \
-    -recoveryGroupName "+$ARCH_DISKGROUP"
+SUDO_ORA_CMD $ORACLE_USER $ENV_DISTID $ORACLE_HOME/bin/dbca -silent \
+-responseFile $REAL_RESPONSE_FILE \
+-variables "ORACLE_BASE_HOME=$ORACLE_HOME,DB_UNIQUE_NAME=$DB_UNIQUE_NAME,ORACLE_BASE=$ORACLE_BASE,PDB_NAME=$PDB_NAME,DB_NAME=$DB_UNIQUE_NAME,ORACLE_HOME=$ORACLE_HOME,SID=$DB_UNIQUE_NAME" \
+-createDatabase \
+-templateName General_Purpose.dbc \
+-gdbname $DB_UNIQUE_NAME \
+-sid $DB_UNIQUE_NAME \
+-nodelist $NODE_LIST \
+-databaseConfigType $CONFIG_TYPE \
+-databaseType $DATABASE_TYPE \
+-createAsContainerDatabase $IS_CDB \
+-numberOfPDBs $PDB_COUNT \
+-pdbName "$PDB_NAME" \
+-characterSet $CHARSET \
+-nationalCharacterSet AL16UTF16 \
+-sysPassword "$CDB_PWD" \
+-systemPassword "$CDB_PWD" \
+-pdbAdminPassword "$PDB_PWD" \
+-dbsnmpPassword "$CDB_PWD" \
+-asmsnmpPassword "$CDB_PWD" \
+-automaticMemoryManagement $AUTO_MEMORY \
+-memoryPercentage $MEM_PERCENTAGE \
+-emConfiguration NONE \
+-ignorePreReqs \
+-storageType $STORAGE_TYPE \
+-diskGroupName "+$DATA_DISKGROUP/{DB_UNIQUE_NAME}/" \
+-datafileDestination "+$DATA_DISKGROUP/{DB_UNIQUE_NAME}/" \
+-recoveryAreaDestination "+$ARCH_DISKGROUP" \
+-recoveryGroupName "+$ARCH_DISKGROUP"
 
 #集群验证
 SUDO_CMD_CONT $ORACLE_USER crsctl stat res -t
