oracle install

diff --git a/scripts/DataBase/oracle/install/19c-rac/dbins b/scripts/DataBase/oracle/install/19c-rac/dbins
--- a/scripts/DataBase/oracle/install/19c-rac/dbins
+++ b/scripts/DataBase/oracle/install/19c-rac/dbins
@@ -41,16 +41,6 @@ function SUDO_CMD() {
     fi
 }
 
-function setInstallEnv() {
-    EXEC_ENV_TXT=$(echo $EXEC_ENV | perl -pe 's/\\n/\n/g')
-    if [ ! -z "$EXEC_ENV_TXT" ]; then
-        eval "$EXEC_ENV_TXT"
-    else
-        echo "ERROR: Execute env is empty, must defined by option --EXEC_ENV."
-        exit 2
-    fi
-}
-
 function createOraDir() {
     if [ ! -e "$INVENTORY_LOCATION" ]; then
         mkdir -p $INVENTORY_LOCATION
@@ -65,7 +55,20 @@ function createOraDir() {
     DO_CMD chmod -R 775 $ORACLE_BASE
 }
 
+function setInstallEnv() {
+    #输入的EXEC_ENV是textarea格式，把符号'\n'替换为真正的换行符号
+    #然后eval为shell的变量
+    EXEC_ENV_TXT=$(echo $EXEC_ENV | perl -pe 's/\\n/\n/g' | perl -pe 's/\s*=\s*/=/g')
+    if [ ! -z "$EXEC_ENV_TXT" ]; then
+        eval "$EXEC_ENV_TXT"
+    else
+        echo "ERROR: Execute env is empty, must defined by option --EXEC_ENV."
+        exit 2
+    fi
+}
+
 function setOracleSidInProfile() {
+    #给profile里设置的ORACLE_SID加上序号
     ORACLE_USER_HOME=$(eval echo ~$ORACLE_USER)
     SEQ_NO=$(hostname | perl -pe 's/[^\d]*//g')
     perl -i -pe s'/(ORACLE_SID=\S+)/${1}'$SEQ_NO'/' "$ORACLE_USER_HOME/.bash_profile"
@@ -134,7 +137,7 @@ setInstallEnv
 setOracleSidInProfile
 createOraDir
 
-#unzip安装包到$ORACLE_HOME下，chown oracle:oinstall
+#把参数里的响应文件拷贝到reponse目录，作为静默安装响应文件的基础响应，参数定义部分属性会覆盖此响应文件
 if [ ! -z "$RESPONSE_FILE"]; then
     RESPONSE_FILE=${RESPONSE_FILE#*\"}
     RESPONSE_FILE=${RESPONSE_FILE%%\"*}
@@ -156,7 +159,6 @@ else
 fi
 
 #静默安装DB软件
-#su - oracle
 SUDO_CMD $ORACLE_USER $ORACLE_HOME/runInstaller -silent -force -noconfig -ignorePrereq \
     -responseFile $REAL_RESPONSE_FILE \
     oracle.install.option=INSTALL_DB_SWONLY \
