oracle install uninstall

diff --git a/scripts/DataBase/oracle/install/rac/add-grid-node b/scripts/DataBase/oracle/install/rac/add-grid-node
--- a/scripts/DataBase/oracle/install/rac/add-grid-node
+++ b/scripts/DataBase/oracle/install/rac/add-grid-node
@@ -23,12 +23,12 @@ function SUDO_ORA_CMD() {
     exitCode=$?
     if [ $exitCode -ge 128 ]; then
         #负数返回码，大于127就是负数的补码
-        echo "ERROR: Installation failed, exitCode:$exitCode."
+        echo "ERROR: Execute command failed, exitCode:$exitCode."
         exit $exitCode
     elif [ $exitCode -gt 0 ]; then
-        echo "WARN: Installation has some warning, exitCode:$exitCode."
+        echo "WARN: Execute command  has some warning, exitCode:$exitCode."
     else
-        echo "FINE: All installations were successful."
+        echo "FINE: All operations were successful."
     fi
 }
 
@@ -58,8 +58,20 @@ function parseOpts() {
                 CV_ASSUME_DISTID="${!OPTIND}"
                 OPTIND=$(($OPTIND + 1))
                 ;;
-            ORACLE_USER)
-                ORACLE_USER="${!OPTIND}"
+            GRID_USER)
+                GRID_USER="${!OPTIND}"
+                OPTIND=$(($OPTIND + 1))
+                ;;
+            NODE_NAME)
+                NODE_NAME="${!OPTIND}"
+                OPTIND=$(($OPTIND + 1))
+                ;;
+            NODE_VIP_NAME)
+                NODE_VIP_NAME="${!OPTIND}"
+                OPTIND=$(($OPTIND + 1))
+                ;;
+            NODE_TYPE)
+                NODE_TYPE="${!OPTIND}"
                 OPTIND=$(($OPTIND + 1))
                 ;;
             *)
@@ -84,13 +96,13 @@ function parseOpts() {
 
 parseOpts "$@"
 
-if [ -z "$ORACLE_USER" ]; then
-    ORACLE_USER=oracle
+if [ -z "$GRID_USER" ]; then
+    GRID_USER=grid
 fi
 
-ORACLE_UID=$(id -u $ORACLE_USER 2>/dev/null)
+ORACLE_UID=$(id -u $GRID_USER 2>/dev/null)
 if [ -z "$ORACLE_UID" ]; then
-    echo "WARN: User $ORACLE_USER not exists, maybe already uninstalled."
+    echo "WARN: User $GRID_USER not exists, maybe already uninstalled."
 fi
 
 ENV_DISTID=""
@@ -98,25 +110,34 @@ if [ "$CV_ASSUME_DISTID" != "AUTO" ]; then
     ENV_DISTID="CV_ASSUME_DISTID=$CV_ASSUME_DISTID"
 fi
 
-oraEnv=$(SUCALL_ORA_CMD $ORACLE_USER env | grep ORACLE_)
+oraEnv=$(SUCALL_ORA_CMD $GRID_USER env | grep ORACLE_)
 echo "$oraEnv"
 EXEC_ENV=$oraEnv
 setInstallEnv
 
-SUDO_ORA_CMD crsctl delete node -n $NODE
-
-exitCode=$?
-if [ $exitCode -ge 128 ]; then
-    echo "WARN: Update inventory failed."
-    exit $exitCode
+#========开始执行删除操作==============================
+if [ -z "$INVENTORY_LOCATION" ]; then
+    INVENTORY_LOCATION=$(cat $ORACLE_HOME/oraInst.loc | grep inventory_loc | sed s'/inventory_loc\s*=\s*//' | sed s'/\s*$//')
 fi
 
-su - $GRID_USER olsnodes -s -t
-su - $GRID_USER cluvfy stage -post nodedel -n node_list -verbose
+if [ -z "$INVENTORY_LOCATION" ]; then
+    echo "ERROR: Can not determin invertory directory by file:$GRID_HOME/oraInst.loc."
+    exit 3
+fi
 
-#补充执行清除vip
-su - $GRID_USER srvctl stop vip -i $NODE
-su - $GRID_USER srvctl remove vip -i $NODE -f
-su - $GRID_USER crsctl stat res -t
+echo "Try to verify add node preparation..."
+SUDO_ORA_CMD $GRID_USER $ENV_DISTID $ORACLE_HOME/bin/cluvfy stage -pre nodeadd -n $NODE_NAME -verbose -fixup
+
+echo "Try to execute addnode command to add node $NODE for cluster..."
+if [ "$NODE_TYPE" != "none" ]; then
+    SUDO_ORA_CMD $GRID_USER $ENV_DISTID IGNORE_PREADDNODE_CHECKS=Y $ORACLE_HOME/addnode/addnode.sh -silent -ignorePrereq \
+        "CLUSTER_NEW_NODES={$NODE_NAME}" \
+        "CLUSTER_NEW_VIRTUAL_HOSTNAMES={$NODE_VIP_NAME}" \
+        "CLUSTER_NEW_NODE_ROLES={$NODE_TYPE}"
+else
+    SUDO_ORA_CMD $GRID_USER $ENV_DISTID IGNORE_PREADDNODE_CHECKS=Y $ORACLE_HOME/addnode/addnode.sh -silent -ignorePrereq \
+        "CLUSTER_NEW_NODES={$NODE_NAME}" \
+        "CLUSTER_NEW_VIRTUAL_HOSTNAMES={$NODE_VIP_NAME}"
+fi
 
 exit $HAS_ERROR
